spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MJ?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8081


jwt:
  secret: $2a$04$4mrJX.XBfqh4uGtXzveSKOuHGie8tlT.0..hbf5JRJ77Xtb462xj2
  time: 14400000
  update: 3600000